title: Nathan Phillips Resume
profile_img: /assets/NSPHeadshot.jpg
icon_img: /assets/NSPHeadshot.jpg

name: "Nathan Phillips"
job: " Studying Computer Engineering at the University of Kansas "

phone_number: (913) 313-8257
address: Shawnee, KS
email: nathan.s.phillips@outlook.com
linkedin_username: Nathan Philips
github_username: NSP13737
#instagram_username: instagram
#twitter_username: twitter
#facebook_username: facebook
youtube_username: bossbam
#blog_url: homepage-url

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
